Edit Item Form Modal
ReCoded-Org/IQLBPS-Dilmun pull request #117
Opened 2022-11-15 16:42 UTC by sarahaboudalal

2022-11-15 16:57 UTC, OussamaMasri approved these changes
Great work Sarah!

2022-11-15 17:57 UTC, ayubabdullah approved these changes
Good work sara 😎👌

2022-11-16 10:53 UTC, Iseluin requested changes
Nice job! Can you check the comment and adjust your code ? Also, it would be nice if we would let users to close the modal with an "X" too and by clicking outside the modal.

2022-11-16 10:53 UTC, Iseluin commented on src/components/ItemEditForm/EditItemModal.jsx
> +];
This is iterating in both the new modal and our currently merged form, can you move these inside a "constants" file in src/utils in both components, so DRY code.

2022-11-16 16:55 UTC, haboosh92 commented
Great work , very nice design and clean code

2022-11-16 16:56 UTC, haboosh92 approved these changes
Great jog

2022-11-16 17:18 UTC, Iseluin approved these changes
Noice 👍🏻

2022-11-16 17:18 UTC, merged