22 create home page for signed in users
ReCoded-Org/IQLBPS-Dilmun pull request #133
Opened 2022-11-18 20:45 UTC by OmarBassatni97

2022-11-18 21:37 UTC, OussamaMasri approved these changes
Great Job Guys as always
small suggestions
can we just remove the edit button from the HomeScreen because it doesn't make any sense 
and Idk why but I felt that dog is really staring at my soul :)
so if we can make it a bit smaller(the cards) that would be perfect 
other then that You guys did an Amazing Job

2022-11-18 21:43 UTC, OmarBassatni97 commented
> Great Job Guys as always small suggestions can we just remove the edit button from the HomeScreen because it doesn't make any sense and Idk why but I felt that dog is really staring at my soul :) so if we can make it a bit smaller(the cards) that would be perfect other then that You guys did an Amazing Job

Yeah of course it doesn't make sense but its not me who placed it there that's why I didn't change anything there and for the ItemCard this is just for the Demo we are still waiting for the ItemCard that will be for the whole project

2022-11-19 10:30 UTC, Iseluin requested changes
Some minor comments, looks good overall!

2022-11-19 10:30 UTC, Iseluin commented on src/Pages/SignedInUsersHomePage/SignedInUsersHomePage.test.js
> +// })
This seems like its not doing anything there, can you delete it ?

2022-11-19 10:30 UTC, Iseluin commented on src/Pages/SignedInUsersHomePage/SignedInUsersHomePage.js
> +            </div>
Can we put a slider in here which showcases items in a slider for each main category that we have ?

2022-11-19 10:30 UTC, Iseluin commented on src/Pages/SignedInUsersHomePage/SignedInUsersHomePage.js
> +                        <Link className='px-3 py-2 rounded bg-secondary ml-2 hover:text-tertiary hover:bg-primary transition duration-300' to={ADD_ITEM_ROUTE}>Add New Item</Link>
Can we make these buttons a bit fancier? Like they dont even need to look like a button with the blue background, we can use icons and show them as links as well.

2022-11-19 10:30 UTC, Iseluin commented on src/Pages/SignedInUsersHomePage/SignedInUsersHomePage.js
> +            <div className=' bg-home-page-for-signed-in-users bg-cover w-full min-h-[40vh] md:min-h-[7p0vh] text-background p-5'>
The resolution of the bg image looks low, can we use a higher resolution one ?

2022-11-19 19:28 UTC, karzan7899 commented
have you updated the tests?

2022-11-19 19:30 UTC, OmarBassatni97 commented
> have you updated the tests?

Yes, now

2022-11-20 22:53 UTC, sarahaboudalal reviewed
Looking good guys, i just have few comments:
1) u have some typos in the hero section, and like add a "?" after the question and stuff, little minor edits basically
2) for the photo slide i suggest u add transitions and duration-300? idk try it out
other than that, it looks good

2022-11-23 17:35 UTC, Iseluin requested changes
Looks gorgeous @OmarBassatni97 @haboosh92 , needs just some small touches:

1. The background image, can you blur it just like what we have on the hero section of the home page?
2. Please make the "Some of our Products" into "Most Recent Items", make it bold and center it.
3. Please make the cards smaller so the user can see them without scrolling down.
4. You can remove the unnecessary components from the app like 404, alert etc.
5. You can make the background image even smaller(Heightwise).

2022-11-23 20:48 UTC, Iseluin approved these changes
Nice!

2022-11-23 20:49 UTC, merged