124 feature multilingual website
ReCoded-Org/IQLBPS-Dilmun pull request #134
Opened 2022-11-19 11:16 UTC by ayubabdullah

adding functionality to change language button and prepare three translation files, Arabic and Kurdish translation is not done yet, I'm working on it, if anyone want to help me in these files please text me I appreciated

2022-11-19 18:32 UTC, OussamaMasri approved these changes
Great Job Ayub !
Very well done

2022-11-20 22:28 UTC, sarahaboudalal commented on public/assets/locales/en/translation.json
> +        "check_out": "Watch Full Video",
this one was "check out this video made by one of our satisfied customers" . i suggest we don't change it

2022-11-20 22:28 UTC, sarahaboudalal commented on public/assets/locales/en/translation.json
> +        "check_out": "Watch Full Video",
this one was "check out this video made by one of our satisfied customers" . i suggest we don't change it

2022-11-20 22:29 UTC, sarahaboudalal commented on public/assets/locales/ar/translation.json
> +        "submit": "يُقدِّم"
let this be "ارسال

2022-11-20 22:30 UTC, sarahaboudalal commented on public/assets/locales/ar/translation.json
> +        "feedback_one_title": "عميل",
زبون

2022-11-20 22:31 UTC, sarahaboudalal commented on public/assets/locales/ar/translation.json
> +        "edit_item_info": "تحرير معلومات العنصر",
instead of تحويل let it be  تعديل

2022-11-20 22:32 UTC, sarahaboudalal commented on public/assets/locales/ar/translation.json
> +        "apply": "يتقدم"
طبّق

2022-11-20 22:32 UTC, sarahaboudalal commented on public/assets/locales/ar/translation.json
> +            "used": "تستخدم",
مستخدم

2022-11-20 22:33 UTC, sarahaboudalal commented on public/assets/locales/ar/translation.json
> +            "donated": "تبرعت",
للتبرع

2022-11-20 22:34 UTC, sarahaboudalal commented on public/assets/locales/ar/translation.json
> +            "crafted": "مصنوع"
صناعة يدوية

2022-11-20 22:34 UTC, sarahaboudalal commented on public/assets/locales/ar/translation.json
> +            "title": "أنواع",
عنوان

2022-11-20 22:36 UTC, sarahaboudalal commented on public/assets/locales/ar/translation.json
> +        "feature_three_title": "يجتمع",
قابل\اجتمع

2022-11-20 22:36 UTC, sarahaboudalal commented on public/assets/locales/ar/translation.json
> +        "feature_three_title": "يجتمع",
قابل\اجتمع

2022-11-20 22:37 UTC, sarahaboudalal commented on public/assets/locales/ar/translation.json
> +        "feature_one_title": "منقي",
فلتر idk if that's even arabic but everyone use that lol

2022-11-20 22:41 UTC, sarahaboudalal commented on public/assets/locales/ar/translation.json
> +        "meet_our_team": "التق بفريقنا"
تعرف على فريقنا

2022-11-20 22:42 UTC, sarahaboudalal commented on public/assets/locales/ar/translation.json
> +        "item_category": "العنصر فئة",
فئة العنصر

2022-11-20 22:42 UTC, sarahaboudalal commented on public/assets/locales/ar/translation.json
> +            "home": "عنصر المنزل"
ادوات منزلية they also should be households in english

2022-11-20 22:43 UTC, sarahaboudalal commented on public/assets/locales/ar/translation.json
> +        "get_started": "البدء"
ابدأ الآن

2022-11-20 22:46 UTC, sarahaboudalal commented on public/assets/locales/ar/translation.json
> +    "not_found": "ربما انتقلت هذه الصفحة؟ هل تم حذفه؟ <br /> هل يختبئ في الحجر الصحي؟ لم تكن موجودة في المقام الأول؟",
تختبئ and  حذفها

2022-11-20 22:47 UTC, sarahaboudalal requested changes
don't even ask me how i did that but i just did it lol. check my comments. but WELL DONE it's epic @ayubabdullah

2022-11-21 06:11 UTC, ayubabdullah commented
> don't even ask me how i did that but i just did it lol. check my comments. but WELL DONE it's epic @ayubabdullah

For the Arabics i used Google translate so any mistake blame google not me LOL 😂 I'll fix them

2022-11-21 12:28 UTC, Iseluin commented
Since this will be a constant WIP until we finish the website, I'm merging this at the end. Sounds good @ayubabdullah ?

2022-11-21 16:13 UTC, ayubabdullah commented
> Since this will be a constant WIP until we finish the website, I'm merging this at the end. Sounds good @ayubabdullah ?

Yep boss sounds good, i will keep updating it until all the components are finished

2022-11-27 15:55 UTC, sarahaboudalal approved these changes

2022-11-27 16:59 UTC, merged