Set up tailwind
ReCoded-Org/IQLBPS-Dilmun pull request #45
Opened 2022-10-25 20:00 UTC by ayubabdullah

installing tailwind CSS as a dev dependency, adding three custom colors ( primary, secondary, black ), and adding the inter-font family as a custom font

2022-10-25 20:04 UTC, Iseluin approved these changes
LGTM, good work 👍🏻

2022-10-25 20:09 UTC, OussamaMasri approved these changes
Great Job Ayub

2022-10-25 20:13 UTC, karzan7899 commented on tailwind.config.js
>    },
keep it up and I will hire you for my company. Great work ma boi!

2022-10-25 20:16 UTC, karzan7899 approved these changes

2022-10-25 20:16 UTC, karzan7899 commented on tailwind.config.js
>    },
good Job, and fast enough. keep it up

2022-10-25 20:19 UTC, MARWAHAKMI commented
@ayubabdullah, could you please remove the package-lock.json file, because there is no need for this other than everything sounds good. Great job, Ayub.

2022-10-25 20:20 UTC, MARWAHAKMI approved these changes
@ayubabdullah, could you please remove the package-lock.json file, because there is no need for this other than everything sounds good. Great job, Ayub.

2022-10-25 20:27 UTC, MARWAHAKMI approved these changes

2022-10-25 20:58 UTC, Iseluin commented
> @ayubabdullah, could you please remove the package-lock.json file, because there is no need for this other than everything sounds good. Great job, Ayub.

It kind of makes sense to add package-lock.json to the .gitignore file, but let me think about that for a while.

2022-10-25 21:22 UTC, MARWAHAKMI commented
> > @ayubabdullah, could you please remove the package-lock.json file, because there is no need for this other than everything sounds good. Great job, Ayub.
> 
> It kind of makes sense to add package-lock.json to the .gitignore file, but let me think about that for a while.

The official documentation says that it's recommended to commit lock file. see this: [npm docs](https://docs.npmjs.com/cli/v6/configuring-npm/package-locks)
but I meant that since we're using yarn for this project, it's better to avoid mixing package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. And to avoid these warnings ` warning package-lock.json found. Your project contains lock files generated by tools
other than Yarn. It is advised not to mix package managers in order to avoid resolution 
inconsistencies caused by unsynchronized lock files. To clear this warning, remove
package-lock.json.`

2022-10-25 21:29 UTC, Iseluin requested changes
To not to create a conflict between package managers, please use yarn every time you add a dependency, so as Marwa pointed out, please delete the package-lock.json and update your pull request @ayubabdullah , otherwise, great work :1

2022-10-25 21:31 UTC, Iseluin commented
> > > @ayubabdullah, could you please remove the package-lock.json file, because there is no need for this other than everything sounds good. Great job, Ayub.
> > 
> > 
> > It kind of makes sense to add package-lock.json to the .gitignore file, but let me think about that for a while.
> 
> The official documentation says that it's recommended to commit lock file. see this: [npm docs](https://docs.npmjs.com/cli/v6/configuring-npm/package-locks) but I meant that since we're using yarn for this project, it's better to avoid mixing package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. And to avoid these warnings ` warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.`

Yup, what I meant was I got to think about including the lock files in general in the commits or not. Because they will create a lot of merge conflicts in the future. Thanks for pointing out the conflicting package managers, I have updated my review.

2022-10-26 06:33 UTC, ayubabdullah commented
> 

Yes sir, i will delete it and push it again, because i use npm that's why in the first i used npm to install tailwind but after that i installed yarn and try to used to it ,

Thanks Marwa, kutay

2022-10-26 06:59 UTC, Iseluin approved these changes

2022-10-26 07:00 UTC, merged