setup the i18next with two different language json file
ReCoded-Org/IQLBPS-Dilmun pull request #52
Opened 2022-10-27 14:55 UTC by viyan-najmaldin

Relates #6

2022-10-27 15:03 UTC, OmarBassatni97 requested changes
Very good stuff, only if you can delete the spaces in the imports section in index.jsx

2022-10-27 15:12 UTC, ayubabdullah approved these changes
great work viyan, but as kutay said we only use yarn not npm so i think the package-lock.json is not required.

2022-10-27 15:14 UTC, ayubabdullah commented on src/i18n.js
> +      loadPath: '/assets/locates/{{lng}}/translation.json',
where the lng variable came from ?

2022-10-27 15:18 UTC, viyan-najmaldin commented on src/i18n.js
> +      loadPath: '/assets/locates/{{lng}}/translation.json',
depend on the languages folder ar or en

2022-10-27 15:22 UTC, viyan-najmaldin commented
> great work viyan, but as kutay said we only use yarn not npm so i think the package-lock.json is not required.



> great work viyan, but as kutay said we only use yarn not npm so i think the package-lock.json is not required.

should I remove it ayub ??

2022-10-27 15:39 UTC, ayubabdullah commented
> > great work viyan, but as kutay said we only use yarn not npm so i think the package-lock.json is not required.
> 
> > great work viyan, but as kutay said we only use yarn not npm so i think the package-lock.json is not required.
> 
> should I remove it ayub ??

kutay told me to remove it

2022-10-27 15:41 UTC, OmarBassatni97 approved these changes
Good Job!

2022-10-27 19:36 UTC, karzan7899 commented on package.json
> +    "i18next-http-backend": "^2.0.0",
I believe this is extra, we don't need it

2022-10-27 19:42 UTC, Iseluin requested changes
Good job @viyan-najmaldin , there are some minor things that I requested, please fix them. Dont forget to delete the `package-lock.json` afterwards since we wont need that file because we are not using npm.

2022-10-27 19:42 UTC, Iseluin commented on package.json
> +    "i18next-http-backend": "^2.0.0",
we dont really need the http-backend package. We can keep it if they were installed via the command automatically though. So no worries on that. But you installed them with npm, we dont use npm. We will add it via yarn. So please uninstall the i18next dependency with `npm uninstall` and add it back again with yarn. If yarn command will give you problems, install yarn by running `npm install -g yarn` then add the i18next dependency with yarn.

2022-10-27 19:42 UTC, Iseluin commented on public/assets/locates/ar/translation.json
> +}
nice structure, we will do stuff like that but we dont need this translation really. So you can delete this and keep the file empty. Other thing is, you have a typo at the folder name. It should be `locales` not `locates` .

2022-10-27 19:42 UTC, Iseluin commented on public/assets/locates/en/translation.json
> +}
same as my comment above, keep this page empty please.

2022-10-27 19:42 UTC, Iseluin commented on src/i18n.js
> +      loadPath: '/assets/locates/{{lng}}/translation.json',
We dont need those 2 lines.

2022-10-27 19:42 UTC, Iseluin commented on src/i18n.js
> +import HttpApi from 'i18next-http-backend';
we dont need this.

2022-10-27 19:42 UTC, Iseluin commented on src/i18n.js
> +    },
In here somewhere, we need a "resources" key which will hold our translation files. Please check the documentation to do that.

2022-10-27 19:42 UTC, Iseluin commented on src/index.jsx
> +import './i18n'
Global imports must be on top, add an empty line and after that add your local imports below it.

2022-10-27 19:54 UTC, OussamaMasri approved these changes

2022-10-28 20:27 UTC, Iseluin approved these changes
LGTM, good work 👍🏻

2022-10-28 20:28 UTC, merged